# Generated by Django 5.2.11 on 2026-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20),
        ),
    ]
