# Generated by Django 5.2.11 on 2026-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20),
        ),
    ]
